### ISSUE TITLE
[Bug]: Won't install on Debian. No instructions provided.

### ISSUE THREAD

**Issue by gnickoloff** [massCodeIO/massCode#103]
### Describe the bug

Installation returns error: cannot find signatures with metadata for snap "masscode_2.6.1_amd64.snap".
Apparently not the only one seeing this issue: https://itsfoss.com/snap-metadata-signature-error/

Looks like it might be a great application, but should install properly with apt. Don't have time to troubleshoot. 

### To reproduce

1. Download the distribution file
2. Attempt to install via "snap"
3. Get error

### Version

2.6.1

### OS

Debian 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by gnickoloff** [comment]
Will install with --dangerous flag. 

Project documentation should be updated to reflect this rather than rely on others to clean up oversights and sloppy documentation.

**Comment by MostHated** [comment]
It would be greatly appreciated if pretty much anything other than snap could be used for linux packaging. deb, flatpak, etc. Just not snap. : (

**Comment by antonreshetov** [comment]
@MostHated https://github.com/massCodeIO/massCode/discussions/87

**Comment by TinajaLabs** [comment]
Hello,
I can find no documentation on the masscode.io site about how to install masscode.  I downloaded it for Linux.  I run Ubuntu 18.04.  I use vscode for my express application.  So...

Usually this can be found as the first section of docs in the get started chapter.  I found a reference (not on the masscode site) that said I should execute the following to install masscode.

`sudo snap install --dangerous`

Why would I install something called dangerous?  ;)

How about a brief line to indicate the exact command for linux?  It would be helpful it is was next to the link to download.  

Pretty please.

Thank you.

**Comment by antonreshetov** [comment]
@TinajaLabs 

Unfortunately I am not a Linux user, the Linux build comes as an addition to macOS and Windows. 

You can read about this problem [here](https://itsfoss.com/snap-metadata-signature-error/). 

I replied earlier, especially for Linux users I've started a discussion here - https://github.com/massCodeIO/massCode/discussions/87

P.S. Closed Issue is not the best and more importantly not a common place for discussion. For this purpose, GitHub gave us an excellent [tool](https://github.com/massCodeIO/massCode/discussions).

**Comment by TinajaLabs** [comment]
I hear you.  When I posted the above, in the discussion section the start discussion button never became active.  I checked the box...  so not sure what else I needed to do to post.  Anyway, I thought the masscode was a linux first app; my incorrect assumption, I suppose.  Moving on.  Thanks.

**Comment by antonreshetov** [comment]
So you can do that. Just do your contribution, that's all. This is still open source, just to consume the work of others and express your dissatisfaction is strange. I'm just one developer on this project and there may be some things I just don't have time to do, have you considered that?

But in general, as I wrote earlier, I bless all the dissatisfied and going forward God.
