### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by davidschubert** [massCodeIO/massCode#119]
### Describe the bug

Please add *.vue Language! :-)

### To reproduce

Just a wish

### Version

latest Version

### OS

macOS Monterey (Intel)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
First for feature please use discuses, second you can use HTML lang for vue, because it's valid HTML.
