### ISSUE TITLE
“massCode” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by gowthammg12** [massCodeIO/massCode#124]
### Describe the bug

Unable to open the massCode app after installing. 

### To reproduce

1. Download the dmg from http://masscode.io/
2. Click on the dmg, drag and drop masscode app to applications
3. Open massCode app
4. Error will be shown "Unable to open the massCode app after installing. Try contacting developer to update the app..."

### Version

2.8.1

### OS

macOS Monterey 12.4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
This is not a bug, this is the usual behavior of the masOS because the application does not have a signature. Go to discussions for this purpose.

**Comment by rtpHarry** [comment]
https://github.com/massCodeIO/massCode/discussions/43
