### ISSUE TITLE
[Bug]: Uncaught exception, pixelated UI

### ISSUE THREAD

**Issue by kaijuh** [massCodeIO/massCode#125]
### Describe the bug

When I start the application, I would sometimes get this js error. After I close the error prompt, It will then open a second  MassCode window without closing the original window.

<img width="416" alt="uncaught exception" src="https://user-images.githubusercontent.com/78699106/178627543-3dffd880-8cc8-4781-890b-c99de6c1afe6.png">

The application itself looks very pixelated but the pixelation goes away if I click on the menu items
<img width="222" alt="pixelated UI" src="https://user-images.githubusercontent.com/78699106/178627612-89631ee4-3eb5-4019-a828-2fb98723e5c9.png">

All of these issues started not in the most recent update but in the one before that
 

### To reproduce

Just open the application

### Version

2.8.1

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Please follow the common rules - one issue one bug
