### ISSUE TITLE
[Bug]: Uncaught Exception

### ISSUE THREAD

**Issue by kaijuh** [massCodeIO/massCode#128]
### Describe the bug

When I start the application, I would sometimes get this js error. After I close the error prompt, It will then open a second MassCode window without closing the original window.
<img width="416" alt="uncaught exception" src="https://user-images.githubusercontent.com/78699106/178731495-20fd1401-2a46-4e77-bc8a-6695e33ffd30.png">

### To reproduce

Just open the application

### Version

2.8.1

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
This is not a bug. The application does not support multi windows. When the application starts, the backend part starts on port 3033. When the second and subsequent copies of the application are launched, port 3033 will be already used. Exactly what is described in the error.

**Comment by kaijuh** [comment]
but how is it not a bug if I am not the one opening a second window? It is the program itself opening the second window, not me

1. I open the program
2.  Error prompt launches
3. I close the error prompt
4. Second MassCode window opens on its own
