### ISSUE TITLE
[Bug]: Pixelated UI

### ISSUE THREAD

**Issue by kaijuh** [massCodeIO/massCode#129]
### Describe the bug

The application itself looks very pixelated but the pixelation goes away if I click on the menu items
pixelated UI

<img width="222" alt="pixelated UI" src="https://user-images.githubusercontent.com/78699106/178731892-4443f5f7-7daf-43d8-b91d-641af6da66e4.png">

### To reproduce

Just open the application

### Version

2.8.1

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by kaijuh** [comment]
The only sequence of actions I did was that I opened the program.  I didn't do anything else

**Comment by kaijuh** [comment]
https://user-images.githubusercontent.com/78699106/178751479-09d00cfa-f224-4ca7-8eaa-897fb8156938.mp4

**Comment by antonreshetov** [comment]
Unfortunately, I can’t reproduce it, there is no Windows 11. It’s probably also related to the monitor’s resolution, system scaling, and so on. In any case, I think that we need to dig into a bunch of electron and system environment.

**Comment by kaijuh** [comment]
what do you mean there is no windows 11?
<img width="382" alt="image" src="https://user-images.githubusercontent.com/78699106/178787719-b69a5187-6b25-4f48-a2d5-eac41e9ccc76.png">

monitor resolution 4k and these are the settings. 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/78699106/178788014-c873c7dc-642c-4b0a-ad85-fa63a7e93aa4.png">

Out of all of the apps I use MassCode is the only one having pixelation issues. Pixelation issues started in the most recent updates

**Comment by antonreshetov** [comment]
I meant I don't have windows 11, I'm a macOS user.

**Comment by kaijuh** [comment]
oh ok. As shown, I use the recommended Windows settings for my monitor so these default settings shouldn't be causing any issues since none of the other apps have this issue. Someone with windows 11 should hopefully be able to give a hand with this.

Cheers
