### ISSUE TITLE
[Bug]: Can't open massCode on this Mac

### ISSUE THREAD

**Issue by rtpHarry** [massCodeIO/massCode#138]
### Describe the bug

App won't run, it just shows this error:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/1038062/179196106-df6f4105-2475-45d2-9fcc-12c8e931a680.png">

My macbookpro is a 2019 intel based one.

### To reproduce

1. Go to website
2. Download the suggested installer for mac
3. Open it and drag the app into the applications folder
4. Run massCode and see error

### Version

2.9.0

### OS

macOS Monterey 12.2.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Use a specific build by arch. 
![image](https://user-images.githubusercontent.com/17480987/179196920-cded4cfd-8769-4c2a-bbf5-d15381a52cf7.png)

**Comment by rtpHarry** [comment]
Thanks, yes this was the issue.

The version that I downloaded was just the one on the website. It auto picked the arch for me, but looking in the trash I can see it gave me the arm64 / apple silicon build.

So this could actually be a bug with the website instead. Just rechecked it now and it's still pointing at the arm64 build:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/1038062/179515704-ba28fa46-0230-461b-b98c-c093a0cd828b.png">

If it's not possible to detect between the two mac arch's then perhaps the wording should be tweaked to say "download for mac silicon" to give a hint that the "other platforms" link should be used instead.
