### ISSUE TITLE
[Bug]: Editor broken

### ISSUE THREAD

**Issue by andrea-citterio** [massCodeIO/massCode#149]
### Describe the bug

![image](https://user-images.githubusercontent.com/26458592/179913390-df1ff099-3e76-42fa-89a3-058cde90b5ff.png)

The position marker does not match the visible line and that makes it incredibly hard to edit a snippet. E.g. : in the photo the marker points to the first char of the line and not to the character visually pointed (between 6 and 0)

### To reproduce

Edit a snippet and go to the end of the line: it will appear way beyond the last characteer

### Version

2.9.0

### OS

Ubuntu

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
I'm not quite sure what you mean. Nevertheless, if it really is a bug, it should be addressed directly to the [Ace](https://github.com/ajaxorg/ace), because massCode uses it without any intervention.

**Comment by andrea-citterio** [comment]
https://design.ubuntu.com/font/ This should be the default font family of ubuntu. I can't tell for all the other Linux distros. Here's a photo with the default font in the ace editor so that you can check for yourself.
![image](https://user-images.githubusercontent.com/26458592/180148114-1596a2f9-70c0-4eae-8bf2-b63659d766cd.png)

![image](https://user-images.githubusercontent.com/26458592/180147811-bd623f63-a135-4df9-9243-b708775653c4.png)

**Comment by antonreshetov** [comment]
I think I will add the next family "SF Mono, Consolas, Menlo, Ubuntu Mono, monospace", the last one will be a fallback if some one is missing. I think this will solve the problem in the future.

**Comment by antonreshetov** [comment]
Closed because it was fixed in [3d9efcd](https://github.com/massCodeIO/massCode/commit/3d9efcdc6dd82d6ae598e160333c3fb116b87aa9)
