### ISSUE TITLE
[Bug]: Folder renaming doesn't work

### ISSUE THREAD

**Issue by sangyuxiaowu** [massCodeIO/massCode#162]
### Describe the bug

After moving the folder directory structure, the right-click menu renaming function does not work.

Test double-click to modify available. The software is normal after restarting.

![111](https://user-images.githubusercontent.com/17669599/180405175-d1fd36e7-bd6c-4c1d-9261-8682694a09eb.gif)

### To reproduce

1. make new folder
2. Drag and drop to modify the folder structure
3.Rename using context menu

### Version

2.10.0

### OS

windwos10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was in #169
