### ISSUE TITLE
[Bug]: Cannot search text in Description

### ISSUE THREAD

**Issue by gumuyueying** [massCodeIO/massCode#173]
### Describe the bug

Can't search keywords from description of a snippet.

### To reproduce

1. Go to "Search".
2. Type some words only in "Description" field of a snippet.
3. No match found.

### Version

2.10.0

### OS

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
It's not a bug. The search is performed only by snippet name or by its body

**Comment by gumuyueying** [comment]
> It's not a bug. The search is performed only by snippet name or by its body

OK, got it.

**Comment by xtremforce** [comment]
> It's not a bug. The search is performed only by snippet name or by its body

Would be a lot of help if we could search by description.
