### ISSUE TITLE
[Bug]: Dart language code formatting not working after select default language

### ISSUE THREAD

**Issue by franklin-vidal** [massCodeIO/massCode#175]
### Describe the bug

Hello,

The code formatting not working with dart.

Great app, thanks for help.

### To reproduce

Select default language.

### Version

2.9.0

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
@franklin-vidal see [docs](https://masscode.io/documentation/essentials/snippets.html#available-languages)
