### ISSUE TITLE
Why the character in snippet title is so ugly?

### ISSUE THREAD

**Issue by i-bugmaker** [massCodeIO/massCode#20]
![image](https://user-images.githubusercontent.com/26687639/163003408-fa0f41e7-f1da-470a-9332-886d6310abcf.png)
Characters like 'q' 'y' 'p' 'g' 'j' display not well in snippet title

massCode Version: 2.0.0-beta.2
OS : Win11 Pro

**Comment by antonreshetov** [comment]
@i-bugmaker Well, I'm not amused, follow the etiquette and code of conduct.

**Comment by i-bugmaker** [comment]
> @i-bugmaker Well, I'm not amused, follow the etiquette and code of conduct.

sorry
