### ISSUE TITLE
[Bug]: After Upgrade snippets gone

### ISSUE THREAD

**Issue by Seulasslintan** [massCodeIO/massCode#216]
### Describe the bug

After I upgrade from version 2.11.0 on Windows to 3.1.0 all snippets are gone. 
Default Folder is displayed all empty.

Checked file Preferences > Storage path

### To reproduce

1. Download 3.1.0 and install
2. Open massCode 
3. Snippets are gone

### Version

3.1.0

### OS

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
This is a very strange situation and no one has ever reported on it. Open db.json in the editor and check for the necessary snippets. A simple update does not lead to a DB overwrite.

**Comment by Seulasslintan** [comment]
Hi @antonreshetov I just downloaded v2.11.0 again and reinstalled it. All snippets are there like before. The json file was filled with my snippets all along, that's the first thing I checked after update to 3.1.0.
I've run the update via winget. I've just downloaded the v3.1.0 manually and installed it again, it's working fine now. 
Maybe some issue with winget or just a temporary issue.
Thanks for your very fast response.

**Comment by antonreshetov** [comment]
Thank goodness.

**Comment by antonreshetov** [comment]
Can we close?

**Comment by Seulasslintan** [comment]
Oh yes please and dig it in a depp hole ;)
