### ISSUE TITLE
Doesn't work on Windows 11

### ISSUE THREAD

**Issue by zbahadir** [massCodeIO/massCode#23]
Doesn't work on Windows 11. Add folder button is not working.

![masscodebata4](https://user-images.githubusercontent.com/3078225/163176664-f7ae9f52-8188-4d01-9c43-497603a5b9ab.png)

Windows 11

**Comment by antonreshetov** [comment]
@zbahadir It seems that you have previously installed version 2.0.0-beta-1 from the old repository, which also has a database file called db.json. Move the old database to another location and restart the application.
