### ISSUE TITLE
[Bug]: Preview Screenshot error

### ISSUE THREAD

**Issue by WJ231009014** [massCodeIO/massCode#240]
### Describe the bug

4 spaces , enter new line and tab(tab size = 4) can column alignment in the code editor, but can't column alignment in preview screenshot.

### To reproduce

1. first line: 4 spaces
2. second line: only enter new line
3. third line: Back to the beginning of the line and use tab(tab size = 4)

in code editor:
![image](https://user-images.githubusercontent.com/41817475/184809692-fd7f9918-8606-4d53-a625-dff9cc641c20.png)

but in preview screenshot:
![image](https://user-images.githubusercontent.com/41817475/184809818-7db54f05-3792-4064-95bf-1f49ed633a05.png)

### Version

3.3.0

### OS

Windows 11

### Validations

- [x] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [x] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by SachitSankhe** [comment]
Hey is this issue still open for grabs?

**Comment by antonreshetov** [comment]
Closed because it was fixed in #321
