### ISSUE TITLE
[Bug]: The editor's body cannot be resized when the Window is resized.

### ISSUE THREAD

**Issue by kawnnor** [massCodeIO/massCode#242]
### Describe the bug

The editor's body cannot be resized when the Window is resized.
![masscode_bug](https://user-images.githubusercontent.com/15528208/184932062-7b248a90-5a1b-4937-94ec-53d1ef2175c6.gif)

### To reproduce

The editor's body cannot be resized when the Window is resized. After the window is resized, click on other snippets to fill the editor with snippets-view.

### Version

3.3.0

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was fixed in #253
