### ISSUE TITLE
[Bug]: Data set is reset after updating software via .exe resulting in data loss

### ISSUE THREAD

**Issue by chaoyu1999** [massCodeIO/massCode#267]
### Describe the bug

Data set is reset after updating software via .exe resulting in data loss.
![image](https://user-images.githubusercontent.com/46945475/187118459-10925afa-17c0-4558-ab99-5e78008bf7ec.png)

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Version

3.4.0

### OS

windwos 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
I am not a Windows user, but in my opinion you can not store data in the application folder, because when you update this folder can be overwritten.

**Comment by chaoyu1999** [comment]
> I am not a Windows user, but in my opinion you can not store data in the application folder, because when you update this folder can be overwritten.

It is recommended to add a cloud synchronization function

**Comment by antonreshetov** [comment]
@antonreshetov Have you read the [documentation](https://masscode.io/documentation/sync.html) before?

**Comment by chaoyu1999** [comment]
> @antonreshetov你以前读过[文档吗？](https://masscode.io/documentation/sync.html)

Sorry, I should have looked at the documentation first

**Comment by antonreshetov** [comment]
I'm closing this Issue because this case is your responsibility.  As I wrote earlier, you should not use the application folder as a place to store the database.
