### ISSUE TITLE
"Preview markdown" is also applied to non-markdown fragments

### ISSUE THREAD

**Issue by dvdmunckhof** [massCodeIO/massCode#27]
Hi, I just upgraded from v1 to v2.0.1 and imported my data. Everything works fine so far, I just found one minor issue regarding the markdown preview. It seems like the markdown preview setting isn't reset when switching fragments.

**Reproduction steps**
1. Create a snippet
2. Set the language to Markdown and add some Markdown text
3. Add a new fragment to the snippet
4. Set the language of the newly created snippet to anything but markdown (HTML for example) and add some content
5. Go back to the first fragment (the Markdown text)
6. Enable the Markdown preview
7. Go back to the 2nd fragment (non-Markdown)

**Expected result**
The content of the 2nd fragment should be shown, with code highlighting.

**Actual result**
The content is rendered as markdown.

**Comment by dvdmunckhof** [comment]
Not related to this issue, but I wanted to thank you for this great tool! It's the only tool I've been able to find that works on Windows, doesn't store snippets in the cloud, allows you to sort snippets and supports a lot of programming languages. 👍

**Comment by antonreshetov** [comment]
@dvdmunckhof thanks! It's very nice to hear.
Launched today on PH https://www.producthunt.com/posts/masscode-2-0

As for the bug, I'll definitely look into it.

**Comment by antonreshetov** [comment]
@dvdmunckhof please try [latest release](https://github.com/massCodeIO/massCode/releases/tag/v2.1.0).

**Comment by dvdmunckhof** [comment]
Can confirm it's fixed, thanks!
