### ISSUE TITLE
[Bug]: 当前逻辑是吧所有代码都放在一个json中，如果内容多了就会存在卡死

### ISSUE THREAD

**Issue by MooBooYoo503217181** [massCodeIO/massCode#287]
### Describe the bug

[Bug]: 当前逻辑是吧所有代码都放在一个json中，如果内容多了就会存在卡死

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..
当前逻辑是吧所有代码都放在一个json中，如果内容多了就会存在卡死

### Version

3.4.1

### OS

window10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
@MooBooYoo503217181 The main language for the repo is English. Please describe the issue in English.

**Comment by MooBooYoo503217181** [comment]
Hello, in the process of using our software, the program will get stuck. Later, we checked the cause and found that our note logic is to put all the code in one json. If there is more content, the program will get stuck. I think our software is good, and I hope it can be optimized.
&nbsp;


芷若初心N?N
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anton ***@***.***&gt;; 
发送时间: 2022年9月29日(星期四) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [massCodeIO/massCode] [Bug]: 当前逻辑是吧所有代码都放在一个json中，如果内容多了就会存在卡死 (Issue #287)





 
@MooBooYoo503217181 The main language for the repo is English. Please describe the issue in English.

**Comment by Qwenjin** [comment]
reproduced  as mentioned above.
