### ISSUE TITLE
Editor -> Format overrides snippets

### ISSUE THREAD

**Issue by rk55edev** [massCodeIO/massCode#29]
**Describe the bug**
Editor -> Format overrides snippets

Hello, i have two snippets. I format the first one using the Editor -> Format function.
If I do the same to the second snippet, the second snippet is overwritten with the first snippet.

**To Reproduce**
1. Go to Menu Editor
2. Click on 'Format'
3. The snippet is formatted correctly
4. Choose a different snippet
5. The current snippet will be overwritten with the previously formatted snippet

**Expected behavior**
no override the current snippet

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.0.1

**Comment by antonreshetov** [comment]
@rk55edev please try [latest release](https://github.com/massCodeIO/massCode/releases/tag/v2.1.0).

**Comment by antonreshetov** [comment]
Closed because it was fixed in #32
