### ISSUE TITLE
[Bug]: Preview screenshot export is not the same as preview

### ISSUE THREAD

**Issue by ollioddi** [massCodeIO/massCode#297]
### Describe the bug

Hi.

I am using the snippet preview screenshot function, however upon saving the result is not as expected.

I am unsure whether this is intended or a bug.

Expected output:
![image](https://user-images.githubusercontent.com/7466744/197497496-8a10108c-8faf-48df-b48c-b9fefab7e0d6.png)

Actual output:
![image](https://user-images.githubusercontent.com/7466744/197497616-41380c19-0866-472d-bc3f-861223829e2d.png)

Issues:

- Wrong aspect ratio
- Corners are cut out (And not rounded)
- Background not present on output
- Margin / padding around buttons missing

Expected:
What is seen in the preview

I could not find any documentation on this feature or ways to customize.

If this is not a bug, then feel free to close the issue.

### To reproduce

1. Go to a snippet
2. View the snippet preview
3. Export the preview
4. Compare

### Version

Version: 3.4.1 Electron: 16.2.3 Chrome: 96.0.4664.174 Node.js: 16.9.1 V8: 9.6.180.23-electron.o OS: Windows NT 10.0.22621

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was fixed in #317
