### ISSUE TITLE
[Bug]: Html output is messy

### ISSUE THREAD

**Issue by christophdoering** [massCodeIO/massCode#309]
### Describe the bug

The exported html is missing a header and doctype. The body and style tags are not closed right. 

```
<html>
    <body><div>Add fragments with HTML & CSS languages to view result.</div><body>
    <style>
    body {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      margin: 0;
      
    }
  body{
color:red;
font-family:sans-serif;
}<style>
  </html>
```

### To reproduce

Export html example.

### Version

3.4.1

### OS

macOS Monterey 12.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was fixed in #320
