### ISSUE TITLE
[Bug]: Code language invisible before selection

### ISSUE THREAD

**Issue by christophdoering** [massCodeIO/massCode#310]
### Describe the bug

After creating a new snippet. The code language is not visible. 
![example](https://user-images.githubusercontent.com/38133778/203499545-5854882c-44cf-4f05-8026-bd8d7d23fdc4.png)

### To reproduce

create a new snippet. 

### Version

Version: 3.4.1

### OS

macOS Monterey 12.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by Faq** [comment]
@christophdoering try record with https://formulae.brew.sh/cask/licecap
