### ISSUE TITLE
[Bug]: Add tags Manager

### ISSUE THREAD

**Issue by zebulondev** [massCodeIO/massCode#332]
### Describe the bug

On db.json we have all tags. But if i need delete a tag?
In json is ok, i can remove it.

But it should be amazing if we haved a tags manager.

### To reproduce

N/A

### Version

3.5.0

### OS

Mac OS (intel)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Try to read doc https://masscode.io/documentation/tags.html before open issue.

**Comment by zebulondev** [comment]
oh sorry ! but it's really too small :D
