### ISSUE TITLE
[Bug]: can't find by tag？

### ISSUE THREAD

**Issue by wonb168** [massCodeIO/massCode#339]
### Describe the bug

masscode can add tag for my code，but can not search it by tag？

### To reproduce

![image](https://user-images.githubusercontent.com/25274931/215378130-1b6c7967-4d95-4aae-87a4-294f85179901.png)
I add a tag named **pg** for my code,
but can use pg to find it in the search box.

### Version

3.4.1

### OS

win10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
This is not a bug. massCode does not provide a search by tags.

**Comment by wonb168** [comment]
> This is not a bug. massCode does not provide a search by tags.

why not provide a search by tags? then why add tags?what's the function of tag?

**Comment by nickdos** [comment]
> why not provide a search by tags? then why add tags?what's the function of tag?

Took me a lot of hunting and searching to find how to use tags, as well. You need to click the top-left corner of the "TAGS" heading, where is appears as `LIBRARY / TAGS`. 

![image](https://github.com/massCodeIO/massCode/assets/532845/253571b7-1abd-4afb-9aa8-88de2d06c30d)

The confusing aspect, is that it looks like a breadcrumb trail (to me, anyway), and so I didn't expect that clicking on it would change the view. It really needs so sort of UI formatting to indicate it is actionable, IMO. This is compounded by the fact that the application does not implement any cursor changes on mouse-over for clickable elements, so when hovering the mouse over those headings, the cursor never changes.
