### ISSUE TITLE
[Bug]: Can't open the app

### ISSUE THREAD

**Issue by Rowdysign** [massCodeIO/massCode#341]
### Describe the bug

Since two weeks I suddenly can't open the app. It gives me the following message: The app Masscode.app can't be openend (it's in Dutch, check the attachment).

![masscode-cant-be-opened](https://user-images.githubusercontent.com/124995483/218031519-4c7449ae-c9c1-4aca-b499-25f3e0ee7fae.png)

I am using a Macbook Pro with MacOS Monterey (version 12.0.1). There is a new update (MacOS Ventura), but I haven't download it yet, could this be the source of the problem?

Is this a bug and how can we solve this? I really like MassCode :-)

### To reproduce

1. Open MassCode-app in MacOS 
2. See the message

### Version

Don't know actually, it's from 18-06-2020

### OS

MacOS Monterey (version 12.0.1)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
@Rowdysign Earlier versions of the application did not have a signature. Try downloading the latest version of the application. https://github.com/massCodeIO/massCode/releases/tag/v3.5.0

**Comment by Rowdysign** [comment]
Downloading the latest version helped solve this problem. Thanks.
