### ISSUE TITLE
[Bug]: Keystrokes occasionally removed

### ISSUE THREAD

**Issue by wchisenski** [massCodeIO/massCode#347]
### Describe the bug

When creating new snippets, massCode occasionally removes keystrokes. I have never seen this behavior within the editor itself, only in the name/title field _(see animated GIF below)_.

![masscode-remove-keystroke](https://user-images.githubusercontent.com/53623427/221306673-91002106-69ec-4b6f-846f-851aa3ee7a65.gif)

### To reproduce

1. Press the `New Snippet` button (+)
2. Start typing name of snippet

### Version

3.6.0

### OS

macOS Ventura 13.2.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was fixed in #351
