### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by heliomcp** [massCodeIO/massCode#35]
Running the latest version on windows 11 (migrating all snippets from old 1.3) the search show always all snippets.

![image](https://user-images.githubusercontent.com/9692595/163614281-25623154-7c38-43a4-8ef5-df0084ee1347.png)

Sshots errors from console after trying to search something
![image](https://user-images.githubusercontent.com/9692595/163617617-09a6df21-7e16-4d7e-9dc1-8864da341e5b.png)
... at the end
![image](https://user-images.githubusercontent.com/9692595/163618158-d2191da4-0ccd-4151-9265-19e84765b088.png)

**Comment by antonreshetov** [comment]
Closed because it not follow bug template.
