### ISSUE TITLE
[Bug]: One TAB stands for tab instead of four spaces

### ISSUE THREAD

**Issue by Justsenger** [massCodeIO/massCode#355]
### Describe the bug

The language I use is python, which has very strict requirements for indentation. However, the tabs of masscode cannot be replaced by four spaces, which is very distressing for me to write code. Is there something I didn't notice? Or a bug?

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Version

3.6.0

### OS

windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by manngo** [comment]
@Justsenger Python’s pretty strict about indentation, but using a tab is just fine — it’s what I use.

However, I have a bug notice about inconsistent behaviour. Pressing a tab on a single line inserts a tab. Highlighting code and pressing tab indents with spaces. Not even the four I have selected. That’s seriously broken, especially if you’re coding with Python. No one seems to have noticed.

Fortunately for me, I use a paid snippets manager for the Mac (SnippetsLab) which I think this one is trying to clone.
