### ISSUE TITLE
[BUG] Could not import database file from Windows  > Mac App

### ISSUE THREAD

**Issue by locvfx** [massCodeIO/massCode#36]
**Describe the bug**
I want to migrate snippets which have been stored in my Desktop PC, windows 10, and import into Mac OS (my Laptop)

Navigated to the target folder, MassCode did not find the file 
in windows: data.json
In mac : db.json

I tried to rename the file to match the filename in Macos but seems the App could not read the file's structure

**Comment by antonreshetov** [comment]
Closed because it not follow bug template.
