### ISSUE TITLE
[Bug]: After I renamed my macOS account, massCode can’t find its files.

### ISSUE THREAD

**Issue by KeKe12030** [massCodeIO/massCode#386]
### Describe the bug

After I renamed my macOS account, massCode can’t find its files.
<img width="520" alt="image" src="https://github.com/massCodeIO/massCode/assets/27548249/63964f01-18cb-4a49-ab36-f59937193da2">
The part blocked by the QR code is my old username.
I tried to delete the file ﻿io.masscode.app.savedState and change the path in the ~/massCode/db.json, but neither of them worked.

### To reproduce

1. Change the username and home folder name in macOS.

### Version

v3.7.0

### OS

macOS Ventura

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Try to delete the values for the following keys - `storagePath`, `backupPath` in `preferences.json`.

`/Users/<your_username>/Library/Application Support/massCode/v2/preferences.json`
