### ISSUE TITLE
[Bug]: 一些可以提升使用体验的地方

### ISSUE THREAD

**Issue by oneTaken** [massCodeIO/massCode#394]
### Describe the bug

版本：最新的3.7.0

1. 发现每次点击`new_folder`的时候都是在根目录新建，新建之后再拖动到想要放置的位置。在多层级目录下带来了非常多的重复性劳动。
2. 文件夹的`default language`只作用于该文件夹，不作用于其子文件夹。其子文件夹仍然是需要重新手动修改。
3. 虽然每个文件可以设置tag，但是搜索的时候实际上是全局文本搜索的，没有作用域，也搜索不了tag，那这个tag起到的作用非常有限。

感谢开发，整体上至少是能用的。

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Version

3.7

### OS

MacOS Ventura 13.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
English please
