### ISSUE TITLE
[Feature]: Requesting the addition of resizable columns for  Left code snippet sub-sections and the ability to copy links for navigation.

### ISSUE THREAD

**Issue by CodeEngieer** [massCodeIO/massCode#414]
### Describe the bug

Hello, MassCode developers! Our project development team has been using your software for code management. Regarding code snippet sub-sections, I hope the new version can add a column and allow for free resizing, rather than being horizontal. This is because there may be several sub-sections under one code snippet, and we'd like to be able to copy links to these sub-sections for easy navigation through the links.

### To reproduce

New Function

### Version

3.7.0

### OS

window11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
For suggestions please use the discussion
