### ISSUE TITLE
[Bug]: Masscode on windows does not have the new Developer Tools menu

### ISSUE THREAD

**Issue by DavidDeboeck** [massCodeIO/massCode#415]
### Describe the bug

Masscode on windows does not have the new Developer Tools menu.
Only following items appear in the masscode menu:

- Preferences
- Check for updates
- Quit masscode

Tested on 2 different windows computers.  The macos version does have the new menus.

### To reproduce

1. Click the "masscode" menu

### Version

3.8.0

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was fixed in #416
