### ISSUE TITLE
[Bug]: using multi device/platform via google drive solution

### ISSUE THREAD

**Issue by darkjackx** [massCodeIO/massCode#426]
### Describe the bug

I found massCode is the most Kickass app for both win/mac.

but this is not very reliable if using multi devices at same time with google drive.
because the app seems don't have ctrl-s/cmd-s for saving database.

the snippets will be missing if both win/mac keep running massCode and add new codes.

they are sharing the same json database.
in mac:
/Users/user/Library/CloudStorage/GoogleDrive-xxxx@gmail.com/mydrive/app-sync

in pc:
G:\.shortcut-targets-by-id\dfgr32rfsg-5wVp_Lke3iWddiL0-Ke\app-sync

### To reproduce

1. pc side open massCode and add some snippets, then keep app running
2. mac side open massCode and add some snippets, then keep app running
3. then close both app.
4. and check the number of snippets in database

### Version

3.1

### OS

win 11, mac 14.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
The app doesn't support any real-time syncronization, so it can't be a bug.
