### ISSUE TITLE
[Bug]: MacOS Unable to open v3.10.0 (arm64)

### ISSUE THREAD

**Issue by pw-64** [massCodeIO/massCode#433]
### Describe the bug

Upon downloading a fresh massCode-3.10.0-arm64.dmg, mounting, and trying to open the app, I get 

"massCode.app" can't be
opened because Apple cannot
check it for malicious software.
This software needs to be updated.
Contact the developer for more
information.

I assume this is probably a code signing / apple developer problem, maybe massCode's key hasn't been renewed?

### To reproduce

1. Go to https://github.com/massCodeIO/massCode/releases/download/v3.10.0/massCode-3.10.0-arm64.dmg
2. Open dmg to mount it
3. Double-click the app

### Version

3.10.0

### OS

MacOS Ventura 13.5.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
https://github.com/massCodeIO/massCode/discussions/413

**Comment by pw-64** [comment]
Thank you.
