### ISSUE TITLE
[Bug]: Missing Snippets

### ISSUE THREAD

**Issue by digital-inception** [massCodeIO/massCode#436]
### Describe the bug

All of my code snippets disappeared.
I opened MassCode on Windows and there no snippets.

### To reproduce

There are no steps to replicate.

### Version

3.10.0

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
More information is needed, perhaps you have moved the database file, because the file cannot just disappear.
