### ISSUE TITLE
[Bug]: Apple Silicon can't open

### ISSUE THREAD

**Issue by eberhapa** [massCodeIO/massCode#437]
### Describe the bug

"can't be opened because Apple cannot check it for malicious software."

### To reproduce

Downloaded newest version but can't open it

### Version

3.10.0

### OS

macOS 14.1.1 (23B81)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
https://github.com/massCodeIO/massCode/discussions/413
