### ISSUE TITLE
Unable to open Application on Mac Silicon

### ISSUE THREAD

**Issue by aravenwood12** [massCodeIO/massCode#442]
### Describe the bug

Running older version of app w/out problems.  Upgraded to new version, and no longer opens, error message saying it cannot be opened because apple cannot check it for malicious software.  Running on MacMini M2 Pro Silicon.  I really like app and wish I could get it going again.

![Screenshot 2024-01-13 at 6 40 35 PM](https://github.com/massCodeIO/massCode/assets/115893689/a875a9bb-e075-45c9-9a9e-718bf5cb5b22)

### To reproduce

download current version from masscode website, install, then try to open

### Version

massCode-3.10.0-arm64.dmg

### OS

MacOS Sonoma 14.1.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by aravenwood12** [comment]
tried to open by bypassing Apple quarantine and get this message - 
![Screenshot 2024-01-13 at 6 49 58 PM](https://github.com/massCodeIO/massCode/assets/115893689/333a090d-8c18-4a6b-9141-ee9fad59579e)


It would be better if it weren't on the quarantine list to begin with.

**Comment by antonreshetov** [comment]
Press open button. 

https://github.com/massCodeIO/massCode/discussions/413
