### ISSUE TITLE
[Bug]: Website Latest Release Page Not Updated

### ISSUE THREAD

**Issue by rtpHarry** [massCodeIO/massCode#459]
### Describe the bug

Just got the update notice in the top right, clicked it, and went through the install process. At the end it was still showing.

When I did "check for updates" from menu, it says latest version is .11 but the website download page is on .10

https://masscode.io/download/latest-release.html

The latest version on GitHub is .11

### To reproduce

1. Go to https://masscode.io/download/latest-release.html
2. See its not the latest version

### Version

3.10.0

### OS

MacOs

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
This repository is only for issues related to the application itself. The website repository is -https://github.com/massCodeIO/masscode.io
