### ISSUE TITLE
[Bug]: VB language not exists

### ISSUE THREAD

**Issue by Ebnerw** [massCodeIO/massCode#466]
### Describe the bug

Unfortunately, the VB language no longer exists

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Version

3.1.1.0

### OS

Win 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Duplicate #418
