### ISSUE TITLE
[Bug]: The search also lists other results in which the search term does not appear

### ISSUE THREAD

**Issue by schieffahrer** [massCodeIO/massCode#469]
### Describe the bug

The exact search in the program still worked until v3.10.0. In the current version, many more search results are now displayed and most of them do not even contain the search term. 

### To reproduce

1. Go to search
2. enter example "samba"
3. Normally I get exactly 1 result, but now over 20

### Version

v3.11.0

### OS

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
This is not a bug, as starting with version [3.11.0](https://github.com/massCodeIO/massCode/releases/tag/v3.11.0), fuzzy search has been added. For exact search, wrap the desired term in quotes.
