### ISSUE TITLE
[Bug]: Nested folder creation does not work

### ISSUE THREAD

**Issue by u3Izx9ql7vW4** [massCodeIO/massCode#471]
### Describe the bug

When right clicking on a folder to create a new folder, the expected behavior should be to create nested folder under the folder that was clicked. Instead the new folder is created at the highest level (default) directory. Because the folders are alphabetically ordered and the new folder starts with "Untitled", if a user has more folders than are visible on screen, namely all folders starting with "U" is truncated, it appears as if no folder was created at all. 

### To reproduce

1. Create a folder either by clicking on the "+" or any other way
2. Right click on that folder that you just created and select in the menu click "New Folder"

### Version

3.11.0

### OS

macOS 14.4.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
This is not a bug, as this functionality has not been implemented. Desired feature, yes.
