### ISSUE TITLE
[Bug]: massCode can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by sjordan1975** [massCodeIO/massCode#484]
### Describe the bug

Trying to install massCode on Mac.

Error the error "massCode can't be opened because Apple cannot check it for malicious software"

See screenshot

<img width="387" alt="Screenshot 2024-09-16 at 8 55 01 AM" src="https://github.com/user-attachments/assets/86a2d6e6-d937-46e1-aa4f-ba84dddbc295">

### To reproduce

1. Download massCode
2. Attempt to install on Mac

### Version

3.11.0

### OS

macOS Sonoma v 14.6.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by bittervan** [comment]
Try to find it in the finder Applications directory, right-click it and choose open. Then it will ask you whether you want to open the app.

**Comment by Aiken1** [comment]
> Try to find it in the finder Applications directory, right-click it and choose open. Then it will ask you whether you want to open the app.

doesnt help:

<img width="327" alt="image" src="https://github.com/user-attachments/assets/5843913d-7af1-423b-8574-3249eaf85af3">
