### ISSUE TITLE
[Bug]: Install over prior edition destroys snippet database

### ISSUE THREAD

**Issue by electric-socket** [massCodeIO/massCode#49]
### Describe the bug

Having an older edition, MassCode advises me there is an update available. I downloaded the latest version. During the install, it notices there is an older version. No warning that installing the new version erases the old database. Fortunately, I only had a handful of items but for a new install to erase old data files is unacceptable behavior.

My System: Win 10 Pro 64-bit Electron 16.0.5 Version 2.2.0

### To reproduce

1. Have an older version installed.
2. Add some snippets
3. Notice update available
4. Quit program, download new version
5. Install new version
6. Run new version
7. Old database is gone (also program settings)
8. [optional] Cry and/or become very angry.

### Version

2.2.0

### OS

Windows 10 Peofessional 64-Bit

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
@electric-socket if you used v1 then just make a migration
