### ISSUE TITLE
[Bug]: Hey Folks

### ISSUE THREAD

**Issue by adilshaikh19** [massCodeIO/massCode#494]
### Describe the bug

MassCode is an excellent product, and I have a suggestion to enhance its functionality. In the section where we add or edit code, could we consider switching the editor to something like Monaco Editor or another advanced code editor? This would provide better flexibility with features like syntax highlighting, code suggestions, and searching within snippets, greatly improving the overall user experience.

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Version

v3.3.0

### OS

windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Use [discussions](https://github.com/massCodeIO/massCode/discussions) for suggestion and so on
