### ISSUE TITLE
Dev Environment Should Check for `os.homedir() + '/massCode/dev`

### ISSUE THREAD

**Issue by jrbgit** [massCodeIO/massCode#5]
To help encourage contributions from the community, there should probably be a section of the README for "setting up your dev". I downloaded the source and found that I had to manually create the `dev` folder inside my `$HOME/massCode`. 

I think that if the `NODE_ENV` is set to Development - it should create this directory automatically, so that the database can be initialized and the app can start the first time when launching the dev locally.

I just grabbed the source and I'm still looking it over in my free time. I realize you just pushed this repo not that long ago, and you may already be aware of this issue. If I have some time, I can look into this while I continue to work my way through the code so far.

Command: `yarn run dev:watch`

Error: 
`[Electron] App threw an error during load`
`[Electron] Error: ENOENT: no such file or directory, open '/Users/username/massCode/dev/db.json`

Expected behaviour:
Missing directory is automatically created so that the db can init

Work Around:
Manually creating the `dev` directory will allow the app to start and init a fresh db.json

**Comment by antonreshetov** [comment]
I appreciate your comment, but it has no value right now. There isn't even an alpha version. It's all still an outline, things can change.

**Comment by reslear** [comment]
same
<img width="372" alt="Screenshot 2022-04-10 at 10 46 35" src="https://user-images.githubusercontent.com/12596485/162608095-b89b2c94-6c0a-492f-b4fe-d35ab1cf180f.png">
