### ISSUE TITLE
[Bug]: Cannot create a new snippet

### ISSUE THREAD

**Issue by manurana** [massCodeIO/massCode#51]
### Describe the bug

Cannot create a new snippet on a fresh install
This is on a 14" Macbook Pro (Apple Silicon), and I have installed the arm version of the app.

### To reproduce

Press the "+" icon on the top (next to search), or do a <kbd>Cmd</kbd> + <kbd>N</kbd>
Nothing happens

I have tried to uninstall, delete the storage, and re-install. No luck.

### Version

2.2.0

### OS

macOS Monterey 12.3

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by manurana** [comment]
![Screen Cast 2022-04-26 at 7 08 02 PM](https://user-images.githubusercontent.com/1749522/165271156-503b143d-cb63-4aa9-bb2b-54fdfaa4c7c1.gif)

**Comment by antonreshetov** [comment]
Unfortunately, this video does not help to understand the cause.

**Comment by antonreshetov** [comment]
@manurana Have you chosen the folder where you want to add the snippet?

**Comment by manurana** [comment]
I have chosen a folder, yes (It was there by default)
<img width="628" alt="image" src="https://user-images.githubusercontent.com/1749522/165283838-f4098b7e-9fa1-400c-8a88-a20f05971093.png">

Folder has been created on the file system, and also has a `db.json` file in it

Yes, I understand it's very difficult to debug. I cannot see any error messages, even in the console.
If you have any suggestions, I can follow them

**Comment by antonreshetov** [comment]
@manurana Your video does not show that you have the Default folder selected, it is not highlighted.

**Comment by manurana** [comment]
@antonreshetov , I highlighted the Inbox and tried it again, same issue.
I also tried to move the storage to a different location. Still no luck.

**Comment by antonreshetov** [comment]
@manurana Again, select the Default folder or some other folder and add a snippet. Snippets are not added to system folders.

**Comment by manurana** [comment]
@antonreshetov . OK , I got it
I was highlighting inbox.

When I highlighted `Default`, now I am able to create a snippet

I think from a UX perspective, either it should be highlighted by default, or the user should be able to create a snippet even without highlighting.

Thanks for walking me through this.

**Comment by antonreshetov** [comment]
@manurana Your manipulation with erasing db.json and creating a new one most likely resulted in keeping the old selected folder in the electron store. But this is an extreme case, I do not think that it is necessary to fix it somehow
