### ISSUE TITLE
[Bug]: Javascript error

### ISSUE THREAD

**Issue by mikeingz** [massCodeIO/massCode#59]
### Describe the bug

Hi,
I was running massCode v1.3.1 without any problem, but after installing 2.5.0, I got this error windows as soon as I run it : 

![image](https://user-images.githubusercontent.com/2438157/165932285-c48883ad-2145-4cd9-b7dc-2bcb31300985.png)

Then I press OK and massCode appears but is unusable (can't add folder or create snippet).

I install massCode 1.3.1 back and everything works fine again.

### To reproduce

step 1 : run MassCode 2.5.0 (or 2.4.0, ir 2.3...)
Done! ;)

### Version

all version 2.x

### OS

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
@mikeingz massCode uses port 3033 for the API. Two possibilities, either you have another version of massCode running or you have something else running on port 3033.

**Comment by antonreshetov** [comment]
From the screenshot, there is a third option - you have blocked the ability to use port 3033.
In any case, this is not a bug.

**Comment by flinthamm** [comment]
If you're running Hyper-V or ICS this port range is often blocked. It would be great if the default (3033) network port could be changed from the command line, rather than having to force or reserve network ports that can be troublesome when running other less flexible services. 
Could this be raised as a feature request?
