### ISSUE TITLE
[Bug]: No Snippets are shown, and no Folders can be created

### ISSUE THREAD

**Issue by undavide** [massCodeIO/massCode#72]
### Describe the bug

Freshly installed 2.5.0 version, two major issues:

1. Open MassCode, no pre-existing snippets are shown (heart-attack follows). You must add a Snippet, _and only then_ old ones show.
2. It's impossible to create Folders, either from the + button in the UI or the File menu.

### To reproduce

See:

https://user-images.githubusercontent.com/5939127/167042027-f9136d29-a541-4713-9105-f51278ff6f2b.mp4

### Version

2.5.0

### OS

macOS Monterey 12.3.1 - M1 Max

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by undavide** [comment]
Further info: I had a previous version installed (tbh can't remember which one); I've updated to the 2.5.0 and the screencast shows what happens as soon as I launch it (first, and subsequent launches, it's always the same).
Thank you!

**Comment by antonreshetov** [comment]
@undavide On this video is difficult to understand what is happening, so unfortunately there is nothing to help and set the label bug.

If you used 1.0 before, then go through the migration. If this extreme case is 2.0.0-beta.1 from an old repo, take a look here #3

**Comment by undavide** [comment]
I believe the previous version I had was a 2 point something, I installed a fresh copy as soon as I got my new M1 Mac (early February). There was little in it, like 2-3 snippets I did _not_ import but created from scratch. If it helps I can provide logs, if you tell me where to look for them :-)

I'm afraid I can't provide more info besides what is shown in the video (it's as simple as "open it and no folders can be created, and previously existing snippets are hidden).

It's a shame because I really loved your app which is very well crafted, but _as is_, it's unusable on my machine. 🤷🏻‍♂️

**Comment by antonreshetov** [comment]
@undavide Shame on who?

> If it helps I can provide logs, if you tell me where to look for them :-)

At least you can open the console and show it in the screenshot. 

Also you can simply delete `db.json` and restart the application and you will get a clean database.

**Comment by undavide** [comment]
Oh, you're right I've forgotten it's an Electron application :-) 
Wiping out completely the `db.json` + backups and starting again solved it (lucky me I haven't lost but a few snippets).

Anyway, here's the error in the console FYI (in case it's useful to deal with similar update issues in the future):

https://user-images.githubusercontent.com/5939127/167090509-d311dbdd-d88d-406e-9688-74ce991586dc.mp4

Thanks

**Comment by antonreshetov** [comment]
@undavide It has nothing to do with the fact that the application is Electron-based. And sarcasm in general is inappropriate. 

According to the console logs, you used 2.0.0-beta.1 from the old repository. I already gave you link #3 to see it.

**Comment by undavide** [comment]
I wasn't being sarcastic at all Anton, I apologise if I sounded like that—maybe we're both just a bit lost in translation here.
All I was saying is that I was sorry to not be able to use your application.
