### ISSUE TITLE
[Bug]: Fragments hidden by Scroll bar

### ISSUE THREAD

**Issue by ahotko** [massCodeIO/massCode#92]
### Describe the bug

When Snippet has a lot of Fragments, they are not visible as they are hidden by horizontal ScrollBar

![image](https://user-images.githubusercontent.com/22200613/173526949-bc7cf53e-686c-4ead-919e-713c2ca08266.png)

### To reproduce

1. Create Snippet
2. Add Fragments until Horizontal Scrollbar appears

### Version

2.6.1

### OS

Windows 10

### Validations

- [x] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was fixed in #105
